require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LobbyistsController do

  # This should return the minimal set of attributes required to create a valid
  # Lobbyist. As you add validations to Lobbyist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LobbyistsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all lobbyists as @lobbyists" do
      lobbyist = Lobbyist.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lobbyists).should eq([lobbyist])
    end
  end

  describe "GET show" do
    it "assigns the requested lobbyist as @lobbyist" do
      lobbyist = Lobbyist.create! valid_attributes
      get :show, {:id => lobbyist.to_param}, valid_session
      assigns(:lobbyist).should eq(lobbyist)
    end
  end

  describe "GET new" do
    it "assigns a new lobbyist as @lobbyist" do
      get :new, {}, valid_session
      assigns(:lobbyist).should be_a_new(Lobbyist)
    end
  end

  describe "GET edit" do
    it "assigns the requested lobbyist as @lobbyist" do
      lobbyist = Lobbyist.create! valid_attributes
      get :edit, {:id => lobbyist.to_param}, valid_session
      assigns(:lobbyist).should eq(lobbyist)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Lobbyist" do
        expect {
          post :create, {:lobbyist => valid_attributes}, valid_session
        }.to change(Lobbyist, :count).by(1)
      end

      it "assigns a newly created lobbyist as @lobbyist" do
        post :create, {:lobbyist => valid_attributes}, valid_session
        assigns(:lobbyist).should be_a(Lobbyist)
        assigns(:lobbyist).should be_persisted
      end

      it "redirects to the created lobbyist" do
        post :create, {:lobbyist => valid_attributes}, valid_session
        response.should redirect_to(Lobbyist.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lobbyist as @lobbyist" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lobbyist.any_instance.stub(:save).and_return(false)
        post :create, {:lobbyist => { "name" => "invalid value" }}, valid_session
        assigns(:lobbyist).should be_a_new(Lobbyist)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Lobbyist.any_instance.stub(:save).and_return(false)
        post :create, {:lobbyist => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lobbyist" do
        lobbyist = Lobbyist.create! valid_attributes
        # Assuming there are no other lobbyists in the database, this
        # specifies that the Lobbyist created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Lobbyist.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => lobbyist.to_param, :lobbyist => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested lobbyist as @lobbyist" do
        lobbyist = Lobbyist.create! valid_attributes
        put :update, {:id => lobbyist.to_param, :lobbyist => valid_attributes}, valid_session
        assigns(:lobbyist).should eq(lobbyist)
      end

      it "redirects to the lobbyist" do
        lobbyist = Lobbyist.create! valid_attributes
        put :update, {:id => lobbyist.to_param, :lobbyist => valid_attributes}, valid_session
        response.should redirect_to(lobbyist)
      end
    end

    describe "with invalid params" do
      it "assigns the lobbyist as @lobbyist" do
        lobbyist = Lobbyist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lobbyist.any_instance.stub(:save).and_return(false)
        put :update, {:id => lobbyist.to_param, :lobbyist => { "name" => "invalid value" }}, valid_session
        assigns(:lobbyist).should eq(lobbyist)
      end

      it "re-renders the 'edit' template" do
        lobbyist = Lobbyist.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Lobbyist.any_instance.stub(:save).and_return(false)
        put :update, {:id => lobbyist.to_param, :lobbyist => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lobbyist" do
      lobbyist = Lobbyist.create! valid_attributes
      expect {
        delete :destroy, {:id => lobbyist.to_param}, valid_session
      }.to change(Lobbyist, :count).by(-1)
    end

    it "redirects to the lobbyists list" do
      lobbyist = Lobbyist.create! valid_attributes
      delete :destroy, {:id => lobbyist.to_param}, valid_session
      response.should redirect_to(lobbyists_url)
    end
  end

end
